CREATE TABLE cats (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    race VARCHAR(50) NOT NULL,
    sex VARCHAR(6) NOT NULL,
    ageInMonths INTEGER NOT NULL,
    description VARCHAR(255) NOT NULL,
    userId VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);