CREATE TABLE match_cats (
    id VARCHAR(255) PRIMARY KEY,
    matchCatId VARCHAR(255) REFERENCES cats(id),
    userCatId VARCHAR(255) REFERENCES users(id),
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);